dist: focal
language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
